// Provider abstraction layer
// Every provider implements: listModels, streamChat, chat, healthCheck, capabilities

export const PROVIDER_IDS = {
  ANTHROPIC: 'anthropic',
  OPENAI: 'openai',
  GROQ: 'groq',
  OPENROUTER: 'openrouter',
  GOOGLE: 'google',
  MISTRAL: 'mistral',
  COHERE: 'cohere',
  XAI: 'xai',
  DEEPSEEK: 'deepseek',
  TOGETHER: 'together',
  FIREWORKS: 'fireworks',
  PERPLEXITY: 'perplexity',
  OLLAMA: 'ollama',
  LMSTUDIO: 'lmstudio',
  AZURE: 'azure',
  CUSTOM: 'custom',
};

export const PROVIDER_META = {
  [PROVIDER_IDS.ANTHROPIC]: {
    name: 'Anthropic',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-20250514',
    apiKeyPlaceholder: 'sk-ant-...',
    modelsEndpoint: null,
    isOpenAICompatible: false,
  },
  [PROVIDER_IDS.OPENAI]: {
    name: 'OpenAI',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.openai.com',
    defaultModel: 'gpt-4o',
    apiKeyPlaceholder: 'sk-...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.GROQ]: {
    name: 'Groq',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.groq.com/openai',
    defaultModel: 'llama-3.3-70b-versatile',
    apiKeyPlaceholder: 'gsk_...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.OPENROUTER]: {
    name: 'OpenRouter',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://openrouter.ai/api',
    defaultModel: 'anthropic/claude-sonnet-4',
    apiKeyPlaceholder: 'sk-or-...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.GOOGLE]: {
    name: 'Google Gemini',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://generativelanguage.googleapis.com',
    defaultModel: 'gemini-2.0-flash',
    apiKeyPlaceholder: 'AIza...',
    modelsEndpoint: '/v1beta/models',
    isOpenAICompatible: false,
  },
  [PROVIDER_IDS.MISTRAL]: {
    name: 'Mistral',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.mistral.ai',
    defaultModel: 'mistral-large-latest',
    apiKeyPlaceholder: '',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.COHERE]: {
    name: 'Cohere',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.cohere.com',
    defaultModel: 'command-r-plus',
    apiKeyPlaceholder: '',
    modelsEndpoint: null,
    isOpenAICompatible: false,
  },
  [PROVIDER_IDS.XAI]: {
    name: 'xAI',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.x.ai',
    defaultModel: 'grok-2',
    apiKeyPlaceholder: 'xai-...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.DEEPSEEK]: {
    name: 'DeepSeek',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.deepseek.com',
    defaultModel: 'deepseek-chat',
    apiKeyPlaceholder: 'sk-...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.TOGETHER]: {
    name: 'Together AI',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.together.xyz',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    apiKeyPlaceholder: '',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.FIREWORKS]: {
    name: 'Fireworks AI',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.fireworks.ai',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    apiKeyPlaceholder: 'fw-...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.PERPLEXITY]: {
    name: 'Perplexity',
    requiresKey: true,
    requiresEndpoint: false,
    defaultEndpoint: 'https://api.perplexity.ai',
    defaultModel: 'llama-3.1-sonar-large-128k-online',
    apiKeyPlaceholder: 'pplx-...',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.OLLAMA]: {
    name: 'Ollama',
    requiresKey: false,
    requiresEndpoint: false,
    defaultEndpoint: 'http://localhost:11434',
    defaultModel: '',
    apiKeyPlaceholder: '',
    modelsEndpoint: '/api/tags',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.LMSTUDIO]: {
    name: 'LM Studio',
    requiresKey: false,
    requiresEndpoint: false,
    defaultEndpoint: 'http://localhost:1234',
    defaultModel: '',
    apiKeyPlaceholder: '',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.AZURE]: {
    name: 'Azure OpenAI',
    requiresKey: true,
    requiresEndpoint: true,
    defaultEndpoint: '',
    defaultModel: 'gpt-4o',
    apiKeyPlaceholder: '',
    modelsEndpoint: '/openai/models',
    isOpenAICompatible: true,
  },
  [PROVIDER_IDS.CUSTOM]: {
    name: 'OpenAI Compatible',
    requiresKey: false,
    requiresEndpoint: true,
    defaultEndpoint: '',
    defaultModel: '',
    apiKeyPlaceholder: '',
    modelsEndpoint: '/v1/models',
    isOpenAICompatible: true,
  },
};

export function getProviderMeta(providerId) {
  return PROVIDER_META[providerId] || PROVIDER_META[PROVIDER_IDS.CUSTOM];
}
